--- #YAML:1.0
name:                Mac-Tie-PList
version:             0.03
abstract:            Parse Apple NSDictionary objects (e.g. Preference Lists)
license:             ~
author:              
    - Gavin Brock <gbrock@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          1.03
    Foundation:                    1
    Tie::Array:                    1.03
    Tie::Hash:                     1.01
    Tie::Scalar:                   1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
